In [1]:
import pandas as pd
import numpy as np 

df = pd.read_csv('Housing.csv')

df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [4]:
print("pandas version:", pd.__version__)
print("numpy version:", np.__version__)

pandas version: 3.0.3
numpy version: 2.5.1

In [5]:
price_series = df['price']

print(price_series)
print(type(price_series))

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64
<class 'pandas.Series'>

In [6]:
print(type(df))
print(df.columns)
print(df.index)

<class 'pandas.DataFrame'>
Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')
RangeIndex(start=0, stop=545, step=1)

In [7]:
print(df.head())

print(df.tail())
print(df.describe())
print(df.info())
print(df.shape)

      price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no
1  12250000  8960         4          4        4      yes        no       no
2  12250000  9960         3          2        2      yes        no      yes
3  12215000  7500         4          2        2      yes        no      yes
4  11410000  7420         4          1        2      yes       yes      yes

  hotwaterheating airconditioning  parking prefarea furnishingstatus
0              no             yes        2      yes        furnished
1              no             yes        3       no        furnished
2              no              no        2      yes   semi-furnished
3              no             yes        3      yes        furnished
4              no             yes        2       no        furnished
       price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
540  1820000  3000         2          1        1      yes        no      yes
541  1767150  2400         3          1        1       no        no       no
542  1750000  3620         2          1        1      yes        no       no
543  1750000  2910         3          1        1       no        no       no
544  1750000  3850         3          1        2      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus
540              no              no        2       no      unfurnished
541              no              no        0       no   semi-furnished
542              no              no        0       no      unfurnished
543              no              no        0       no        furnished
544              no              no        0       no      unfurnished
              price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000

          parking
count  545.000000
mean     0.693578
std      0.861586
min      0.000000
25%      0.000000
50%      0.000000
75%      1.000000
max      3.000000
<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB
None
(545, 13)

In [9]:
df.loc[0:4, ['price', 'area', 'bedrooms']]

      price  area  bedrooms
0  13300000  7420         4
1  12250000  8960         4
2  12250000  9960         3
3  12215000  7500         4
4  11410000  7420         4

In [10]:
df.iloc[0:5, 0:4]

      price  area  bedrooms  bathrooms
0  13300000  7420         4          2
1  12250000  8960         4          4
2  12250000  9960         3          2
3  12215000  7500         4          2
4  11410000  7420         4          1

In [12]:
df["price"]

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [13]:
df[['price', 'area', 'bedrooms']]

        price  area  bedrooms
0    13300000  7420         4
1    12250000  8960         4
2    12250000  9960         3
3    12215000  7500         4
4    11410000  7420         4
..        ...   ...       ...
540   1820000  3000         2
541   1767150  2400         3
542   1750000  3620         2
543   1750000  2910         3
544   1750000  3850         3

[545 rows x 3 columns]

In [14]:
df.groupby("furnishingstatus")["price"].mean()

furnishingstatus
furnished         5.495696e+06
semi-furnished    4.907524e+06
unfurnished       4.013831e+06
Name: price, dtype: float64

In [15]:
df.groupby("furnishingstatus").agg(
    avg_price=("price","mean"),
    max_area=("area","max"),
    total_parking=("parking","sum")
)

                     avg_price  max_area  total_parking
furnishingstatus
furnished         5.495696e+06     13200            124
semi-furnished    4.907524e+06     15600            167
unfurnished       4.013831e+06     16200             87

In [16]:
df.groupby("furnishingstatus")["parking"].sum()

furnishingstatus
furnished         124
semi-furnished    167
unfurnished        87
Name: parking, dtype: int64

In [17]:
pivot = pd.pivot_table(
    df,
    values="price",
    index="furnishingstatus",
    columns="airconditioning",
    aggfunc="mean"
)

pivot

airconditioning             no           yes
furnishingstatus
furnished         4.469500e+06  6.786717e+06
semi-furnished    4.557951e+06  5.778769e+06
unfurnished       3.583342e+06  5.286167e+06

In [18]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [19]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [price, area, bedrooms, bathrooms, stories, mainroad, guestroom, basement, hotwaterheating, airconditioning, parking, prefarea, furnishingstatus]
Index: []

In [20]:
df.dropna()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [21]:
df["parking"] = df["parking"].fillna(df["parking"].mean())

In [22]:
df["price_per_sqft"] = df["price"] / df["area"]

In [23]:
mapping = {"yes":1, "no":0}

df["mainroad"] = df["mainroad"].map(mapping)
df["guestroom"] = df["guestroom"].map(mapping)
df["basement"] = df["basement"].map(mapping)
df["hotwaterheating"] = df["hotwaterheating"].map(mapping)
df["airconditioning"] = df["airconditioning"].map(mapping)
df["prefarea"] = df["prefarea"].map(mapping)

In [24]:
df["bedrooms"] = df["bedrooms"].astype(int)

In [25]:
df.rename(columns={"price":"HousePrice"}, inplace=True)

In [26]:
df.sort_values(by="HousePrice", ascending=False)

,HousePrice,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished,1792.452830
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished,1229.919679
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished,1367.187500
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished,1628.666667
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished,1537.735849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,unfurnished,606.666667
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,semi-furnished,736.312500
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,unfurnished,483.425414
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,furnished,601.374570
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,unfurnished,454.545455

In [27]:
city = pd.DataFrame({
    "furnishingstatus":["furnished","semi-furnished","unfurnished"],
    "Category":["Premium","Standard","Budget"]
})

merged_df = pd.merge(df, city, on="furnishingstatus", how="left")

merged_df.head()

,HousePrice,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft,Category
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished,1792.452830,Premium
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished,1367.187500,Premium
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished,1229.919679,Standard
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished,1628.666667,Premium
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished,1537.735849,Premium